name: 🧩 App does not work
description: Autoscroll does not work in an app. Just tell us which one.
title: 'App: '
labels:
- app
body:
- type: markdown
  attributes:
    value: Just add the app's name to the title. The rest is optional.
- type: dropdown
  id: install
  attributes:
    label: How is it installed?
    description: Skip it if you are not sure.
    options:
    - Native package
    - Flatpak
    - Snap
    - AppImage
- type: textarea
  id: more
  attributes:
    label: More info
